//
// Created by 111 on 2024/7/3.
// 将一些不会变而且复用性强的代码放在这里，可以大幅度减少编译时间,假如这里有修改，记得重新编译，所以说需要一些不会变的代码
//
#pragma once
#include <iostream>
#include <windows.h>
#include <vector>
#include <string>
#include <algorithm>
#include <cmath>
#include <map>
#include <unordered_map>
#include <set>
#include <unordered_set>
#include <queue>
#include <deque>
#include <stack>
#include <list>
#include <sstream>
#include <cstdlib>
#include <ctime>
#include <functional>
#include <numeric>
#include <iomanip>
#include <bitset>
#include <cassert>
#include <chrono>
#include <random>
#include <cstring>
#include <complex>
#include <cctype>
#include <climits>
#include <cstdio>
#include <cstdlib>
#include <cmath>
#include <ctime>
#include <cstring>
#include <cassert>
#include <memory>
#include <tuple>
#include <fstream>
#include <optional>
#include <variant>
#include <any>
#include <future>
#include <mutex>
#include <cmath>
//#include "base/trace_event/trace_event.h"
